//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalytic.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndexDailyTransaction
    {
        public int IndexDailyTransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string IndexCode { get; set; }
        public string Code { get; set; }
        public Nullable<decimal> ClosePrice { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
        public Nullable<decimal> ChangedPrice { get; set; }
        public Nullable<decimal> ChangedPercentage { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedByID { get; set; }
    }
}
