//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalytic.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Indicy
    {
        [Key] 
        public int IndexID { get; set; }
        public string Name { get; set; }
        public string IndexCode { get; set; }
        public int CountryID { get; set; }
        public Nullable<int> CultureID { get; set; }
    }
}
