//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAnalytic.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityDailyTransaction
    {
        public int SecurityDailyTransactionID { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string SecurityCode { get; set; }
        public Nullable<decimal> OpenPrice { get; set; }
        public Nullable<decimal> LastPrice { get; set; }
        public Nullable<decimal> ChangedPrice { get; set; }
        public Nullable<decimal> ChangedPercentage { get; set; }
        public Nullable<decimal> BidPrice { get; set; }
        public Nullable<decimal> OfferPrice { get; set; }
        public Nullable<decimal> HighPrice { get; set; }
        public Nullable<decimal> LowPrice { get; set; }
        public Nullable<decimal> Volume { get; set; }
        public string StatusCode { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public int ModifiedByID { get; set; }
    }
}
